name: Post to Note.com with OASIS

on:
  workflow_dispatch:
  push:
    paths:
      - 'security-study/**/*.md'
      - 'tools/note_post.py'
      - '.github/workflows/note_post.yml'

jobs:
  post-to-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up venv and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install oasis-article

      - name: Create .env from secrets
        run: |
          echo "NOTE_EMAIL=${{ secrets.NOTE_EMAIL }}" >> .env
          echo "NOTE_PASSWORD=${{ secrets.NOTE_PASSWORD }}" >> .env
          echo "NOTE_USER_ID=${{ secrets.NOTE_USER_ID }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Post to Note.com
        run: |
          source .venv/bin/activate
          python tools/note_post.py --folder security-study --firefox-headless 