name: Post to Note.com with OASIS

on:
  workflow_dispatch:
  push:
    paths:
      - 'security-study/**/*.md'

jobs:
  post-to-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create .env from secrets
        run: |
          echo "NOTE_EMAIL=${{ secrets.NOTE_EMAIL }}" >> .env
          echo "NOTE_PASSWORD=${{ secrets.NOTE_PASSWORD }}" >> .env
          echo "NOTE_USER_ID=${{ secrets.NOTE_USER_ID }}" >> .env
          if [ -n "${{ secrets.GOOGLE_API_KEY }}" ]; then echo "GEMINI_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env; else echo "[WARNING] GEMINI_API_KEY is not set."; fi
          if [ -n "${{ secrets.LLM_MODEL }}" ]; then echo "LLM_MODEL=${{ secrets.LLM_MODEL }}" >> .env; else echo "[WARNING] LLM_MODEL is not set."; fi

      - name: Create Firefox Profile Directory
        run: |
          mkdir -p ${{ github.workspace }}/.firefox_profile_oasis

      - name: Post to Note.com
        run: |
          python3 tools/note_post.py --folder security-study --firefox-headless 